# Generated by Django 6.0 on 2026-06-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method_auto',
            field=models.BooleanField(default=True),
        ),
    ]
