# Generated by Django 6.0 on 2026-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_image_productcolor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_code',
            field=models.CharField(help_text='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/colors/'),
        ),
    ]
