# Generated by Django 6.0 on 2026-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_productcolor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
