# Generated by Django 6.0 on 2026-07-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_category_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
