# Generated by Django 6.0 on 2026-07-16 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_customer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsite',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveField(
            model_name='settingsite',
            name='key',
        ),
        migrations.RemoveField(
            model_name='settingsite',
            name='value',
        ),
        migrations.AddField(
            model_name='settingsite',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='allow_contact_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='allow_product_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsite',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='enable_about_us_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='enable_contact_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='enable_coupon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='enable_discount_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='enable_guest_checkout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='enable_newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='enable_wishlist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='footer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='maintenance_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='support_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='twitter_x',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='website_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/favicon/'),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='website_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='website_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/logo/'),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='website_logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='settings/logo_dark/'),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='website_name',
            field=models.CharField(default='TBSAS', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsite',
            name='website_short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='website_title',
            field=models.CharField(default='TB SAS Online Store', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsite',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
