# Generated by Django 6.0 on 2026-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_settingsite_options_remove_settingsite_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermain',
            name='button_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='bannermain',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bannermain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bannermain',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
