# Generated by Django 6.0 on 2026-07-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_options_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
