# Generated by Django 6.0 on 2026-07-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_productcolor_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
