# Generated by Django 6.0 on 2026-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermain',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='bannermain',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bannermain',
            name='show_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bannermain',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
