# Generated by Django 6.0 on 2026-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['display_order']},
        ),
        migrations.RenameField(
            model_name='productspecification',
            old_name='order',
            new_name='display_order',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
