# Generated by Django 6.0 on 2026-08-06 15:02

from django.db import migrations, models


def copy_promos(apps, schema_editor):
    PromoBanner = apps.get_model("store", "PromoBanner")
    BannerMain = apps.get_model("store", "BannerMain")

    for promo in PromoBanner.objects.all().order_by("id"):
        if BannerMain.objects.filter(
            title=promo.title,
            banner_type="promo",
        ).exists():
            continue

        banner = BannerMain(
            title=promo.title,
            button_link=promo.link,
            is_active=promo.is_active,
            order=promo.order,
            banner_type="promo",
            description="",
            button_text="",
            show_button=False,
            open_in_new_tab=False,
        )

        # فایل عکس همان‌جا می‌ماند؛ فقط مسیرش به مدل جدید منتقل می‌شود
        if promo.image:
            banner.picture.name = promo.image.name

        banner.save()


def reverse_promos(apps, schema_editor):
    BannerMain = apps.get_model("store", "BannerMain")
    BannerMain.objects.filter(banner_type="promo").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermain',
            name='banner_type',
            field=models.CharField(choices=[('slider', 'Slider'), ('promo', 'Promo')], default='slider', max_length=10, verbose_name='Type'),
        ),
        migrations.RunPython(copy_promos, reverse_promos),
        migrations.DeleteModel(
            name='PromoBanner',
        ),
    ]
