# Generated by Django 6.0 on 2026-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_delete_promobanner_bannermain_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_laptop',
            field=models.BooleanField(default=False, verbose_name='Show in Best Laptops'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_mobile',
            field=models.BooleanField(default=False, verbose_name='Show in Mobile Bests'),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='home_laptop_title',
            field=models.CharField(blank=True, default='Best Laptops', max_length=100, verbose_name='Laptop Section Title'),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='home_mobile_title',
            field=models.CharField(blank=True, default='Mobile Bests', max_length=100, verbose_name='Mobile Section Title'),
        ),
    ]
