# Generated by Django 6.0 on 2026-08-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_brand_is_laptop_brand_is_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('mission', 'Mission / Text'), ('stat', 'Stat'), ('feature', 'Feature'), ('team', 'Team Member'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='e.g. fa-solid fa-rocket', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
