# Generated by Django 6.0 on 2026-08-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_aboutussection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ویژگی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('display_name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('icon', models.CharField(blank=True, help_text='آیکون FontAwesome', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('filter_type', models.CharField(choices=[('checkbox', 'چک\u200cباکس (چندانتخابی)'), ('radio', 'رادیو (تنها یک انتخاب)'), ('range', 'محدوده (برای مقادیر عددی)'), ('color', 'انتخاب رنگ')], default='checkbox', max_length=20, verbose_name='نوع فیلتر')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['filter_display_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='filter_display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش در فیلتر'),
        ),
        migrations.AddField(
            model_name='category',
            name='filter_icon',
            field=models.CharField(blank=True, help_text='آیکون FontAwesome مثل fa-mobile-alt', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_filter',
            field=models.BooleanField(default=True, verbose_name='نمایش در فیلتر دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='filter_display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام نمایش در فیلتر'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='is_filterable',
            field=models.BooleanField(default=False, verbose_name='قابل فیلتر کردن'),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('display_value', models.CharField(blank=True, max_length=100, verbose_name='مقدار نمایشی')),
                ('color_code', models.CharField(blank=True, help_text='کد رنگ برای نوع color مثل #FF0000', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.productattribute')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
                'ordering': ['display_order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='store.product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productattributevalue')),
            ],
            options={
                'verbose_name': 'انتساب ویژگی به محصول',
                'verbose_name_plural': 'انتساب\u200cهای ویژگی\u200cها',
                'unique_together': {('product', 'attribute', 'value')},
            },
        ),
    ]
