# Generated by Django 6.0 on 2026-09-02 12:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_productattribute_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Normalized to uppercase at lookup.', max_length=50, unique=True, verbose_name='Coupon code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Percentage off (0 = no percentage discount). Must be non-negative.', verbose_name='Discount percent')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed amount off (0 = no fixed discount). Must be non-negative.', max_digits=10, verbose_name='Fixed discount amount')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Optional start date/time.', null=True, verbose_name='Valid from')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Optional expiration date/time.', null=True, verbose_name='Valid until')),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Subtotal must meet or exceed this value for coupon to apply.', max_digits=10, verbose_name='Minimum subtotal')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('1000000'), help_text='Cap on percentage-based discount. Null/blank = no cap.', max_digits=10, null=True, verbose_name='Maximum discount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, default=1, help_text='Maximum redemptions. Null/blank = unlimited.', null=True, verbose_name='Usage limit')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times redeemed (updated at checkout).', verbose_name='Usage count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-is_active', 'code'],
                'indexes': [models.Index(fields=['is_active', 'code'], name='store_coupo_is_acti_678532_idx')],
            },
        ),
    ]
