# Generated by Django 6.0 on 2026-09-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, help_text='ProductColor selected at time of order creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productcolor', verbose_name='Selected color'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Snapshot of product final price at time of order creation.', verbose_name='Unit price at purchase'),
        ),
    ]
