# Generated by Django 6.0 on 2026-09-04 12:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_orderitem_price_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', help_text='Coupon code used at order creation (historical record).', max_length=50, verbose_name='Applied coupon code'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount amount applied at order creation (historical record).', max_digits=10, verbose_name='Discount amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Server-side unique key to prevent duplicate order creation from repeated POST submissions.', max_length=64, null=True, unique=True, verbose_name='Idempotency key'),
        ),
    ]
